#!/usr/bin/env bash
#
# Copy the shared prompt into each repo's AGENTS.md as a managed block.
#
#   ./sync.sh                 write the block into every repo in ./targets
#   ./sync.sh <path> ...      write it into these repos instead
#   ./sync.sh --check [...]   report which repos are stale; exit 1 if any are
#
# The block exists because a cloud session starts from a clone and never sees
# ~/CLAUDE.md, and because Codex has no way to reference a file it isn't given:
# inside a repo, the shared rules have to be in that repo's AGENTS.md verbatim.
# So this is deliberate duplication — generated and verified, rather than
# hand-maintained and quietly drifting, which is how it went wrong before.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE="$REPO/AGENTS.md"

BEGIN='<!-- BEGIN SHARED: ninjudd/agent-config -->'
END='<!-- END SHARED -->'
NOTE='<!-- Generated by agent-config/sync.sh. Edit that repo, not this block. -->'

check_only=false
[ "${1:-}" = "--check" ] && { check_only=true; shift; }

if [ $# -gt 0 ]; then
  targets=("$@")
else
  [ -f "$REPO/targets" ] || { echo "no targets file and no paths given" >&2; exit 64; }
  targets=()
  while read -r line; do
    line="${line%%#*}"; line="${line// /}"
    [ -n "$line" ] && targets+=("${line/#\~/$HOME}")
  done < "$REPO/targets"
fi

block="$(mktemp)"; body="$(mktemp)"; out="$(mktemp)"
trap 'rm -f "$block" "$body" "$out"' EXIT

# Refuse to run on a source that isn't there or has been truncated. Without
# this a missing or emptied AGENTS.md renders an empty block and every target
# is "synced" into losing the shared rules, reporting success as it goes.
[ -s "$SOURCE" ] || { echo "$SOURCE is missing or empty; refusing to sync" >&2; exit 1; }

# The source's H1 is dropped: the target already has its own title, and two
# level-one headings in one file read as two documents.
awk 'NR==1 && /^# / { skip=1; next } skip && NF==0 { skip=0; next } { print }' "$SOURCE" > "$body"
[ -s "$body" ] || { echo "$SOURCE has no content below its title; refusing to sync" >&2; exit 1; }

# The rendered block: markers, a note that it is generated, then the prompt.
{ printf '%s\n%s\n\n' "$BEGIN" "$NOTE"; cat "$body"; printf '\n%s\n' "$END"; } > "$block"

# Replace an existing block, or insert one after the file's H1 so the title
# stays first and repo-specific sections still come after the shared rules.
render() {
  local blockfile="$1" file="$2"
  if grep -qF "$BEGIN" "$file"; then
    awk -v b="$BEGIN" -v e="$END" -v blockfile="$blockfile" '
      BEGIN { while ((getline l < blockfile) > 0) block = block l "\n" }
      $0 == b { printf "%s", block; skipping = 1; next }
      $0 == e { skipping = 0; next }
      skipping { next }
      { print }
    ' "$file"
  else
    # The H1 has to be a real heading. A line like "# not a heading" inside a
    # fenced code block is not one, and inserting there corrupts the fence.
    awk -v blockfile="$blockfile" '
      BEGIN { while ((getline l < blockfile) > 0) block = block l "\n" }
      /^```/ { fence = !fence }
      { print }
      !done && !fence && /^# / { print ""; printf "%s", block; done = 1 }
      END { if (!done) printf "%s", block }
    ' "$file"
  fi
}

rc=0
for target in "${targets[@]}"; do
  file="$target/AGENTS.md"
  name="$(basename "$target")"
  if [ ! -f "$file" ]; then
    printf '%-10s %s\n' "no-file" "$name"; rc=1; continue
  fi
  render "$block" "$file" > "$out"
  if cmp -s "$out" "$file"; then
    printf '%-10s %s\n' "ok" "$name"
  elif $check_only; then
    printf '%-10s %s\n' "stale" "$name"; rc=1
  else
    cp "$out" "$file"
    printf '%-10s %s\n' "synced" "$name"
  fi
done

if $check_only && [ $rc -ne 0 ]; then
  echo
  echo "Run agent-config/sync.sh to update these, then commit the result."
fi
exit $rc
